img_wh: [854, 480] # Adjust based on your video resolution
canonical_wh: [1000, 520]

lr: 0.001
flow_loss: 1.0 # Weight for flow consistency loss
flow_step: -1  # Start flow loss immediately

# Encoding settings
N_xyz_w: [8]
deform_hash: True
vid_hash: True

# Training schedule
num_steps: 10001
decay_step: [2500, 5000, 7500]
annealed_begin_step: 4000
annealed_step: 4000
save_model_iters: 2000

fps: 15